/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountBalance } from './accountBalance';

/**
* OBADA account
*/
export class Account {
    /**
    * Account address associated name
    */
    'name'?: string;
    /**
    * Public key
    */
    'pubKey'?: string;
    /**
    * OBADA address
    */
    'address'?: string;
    'balance'?: AccountBalance;
    'nftCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "pubKey",
            "baseName": "pub_key",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "AccountBalance"
        },
        {
            "name": "nftCount",
            "baseName": "nft_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Account.attributeTypeMap;
    }
}

