/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Account } from './account';

export class Accounts {
    'hdAccounts'?: Array<Account>;
    'importedAccounts'?: Array<Account>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hdAccounts",
            "baseName": "hd_accounts",
            "type": "Array<Account>"
        },
        {
            "name": "importedAccounts",
            "baseName": "imported_accounts",
            "type": "Array<Account>"
        }    ];

    static getAttributeTypeMap() {
        return Accounts.attributeTypeMap;
    }
}

