/**
 * OBADA Client Helper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LocalObitDocuments } from './localObitDocuments';
import { LocalObitMetadata } from './localObitMetadata';
import { LocalObitStructuredData } from './localObitStructuredData';

export class ClientObit {
    'id'?: number;
    'obitDid'?: string;
    'usn'?: string;
    'ownerDid'?: string;
    /**
    * Represent available Obit statuses:   - FUNCTIONAL   - NON_FUNCTIONAL   - DISPOSED   - STOLEN   - DISABLED_BY_OWNER 
    */
    'obitStatus'?: ClientObit.ObitStatusEnum;
    'manufacturer'?: string;
    'partNumber'?: string;
    'serialNumberHash'?: string;
    'modifiedAt'?: Date;
    'rootHash'?: string;
    /**
    * Get description from Rohi
    */
    'metadata'?: Array<LocalObitMetadata>;
    /**
    * To generate this link, take an SHA-256 hash of the document, and link to it as https://www.some-website.com?h1=hash-of-document. Note this does not yet adhere to the hashlink standard. 
    */
    'documents'?: Array<LocalObitDocuments>;
    /**
    * Same as metadata but bigger. Key (string) => Value (string) (hash per line sha256(key + value))
    */
    'structuredData'?: Array<LocalObitStructuredData>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "obitDid",
            "baseName": "obit_did",
            "type": "string"
        },
        {
            "name": "usn",
            "baseName": "usn",
            "type": "string"
        },
        {
            "name": "ownerDid",
            "baseName": "owner_did",
            "type": "string"
        },
        {
            "name": "obitStatus",
            "baseName": "obit_status",
            "type": "ClientObit.ObitStatusEnum"
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "string"
        },
        {
            "name": "partNumber",
            "baseName": "part_number",
            "type": "string"
        },
        {
            "name": "serialNumberHash",
            "baseName": "serial_number_hash",
            "type": "string"
        },
        {
            "name": "modifiedAt",
            "baseName": "modified_at",
            "type": "Date"
        },
        {
            "name": "rootHash",
            "baseName": "root_hash",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "Array<LocalObitMetadata>"
        },
        {
            "name": "documents",
            "baseName": "documents",
            "type": "Array<LocalObitDocuments>"
        },
        {
            "name": "structuredData",
            "baseName": "structured_data",
            "type": "Array<LocalObitStructuredData>"
        }    ];

    static getAttributeTypeMap() {
        return ClientObit.attributeTypeMap;
    }
}

export namespace ClientObit {
    export enum ObitStatusEnum {
        Functional = <any> 'FUNCTIONAL',
        NonFunctional = <any> 'NON_FUNCTIONAL',
        Disposed = <any> 'DISPOSED',
        Stolen = <any> 'STOLEN',
        DisabledByOwner = <any> 'DISABLED_BY_OWNER'
    }
}
