/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Device Document
*/
export class DeviceDocument {
    /**
    * Associative name of device document
    */
    'name': string;
    'documentFile': string;
    /**
    * If true then client helper will encrypt document with account key
    */
    'shouldEncrypt'?: boolean = false;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "documentFile",
            "baseName": "document_file",
            "type": "string"
        },
        {
            "name": "shouldEncrypt",
            "baseName": "should_encrypt",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return DeviceDocument.attributeTypeMap;
    }
}

