/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Document hashlink
*/
export class Document {
    /**
    * Associative name of file
    */
    'name'?: string;
    /**
    * Link to the document
    */
    'uri'?: string;
    /**
    * Hash of the file
    */
    'hash'?: string;
    /**
    * If true then client helper will encrypt document with account key
    */
    'encrypted'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "encrypted",
            "baseName": "encrypted",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Document.attributeTypeMap;
    }
}

