/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Generate Obit checksum payload
*/
export class GenerateObitChecksumRequest {
    /**
    * Manufacturer (Required)
    */
    'manufacturer': string;
    /**
    * Part Number (Required)
    */
    'partNumber': string;
    /**
    * Serial Number (Required)
    */
    'serialNumber': string;
    /**
    * Metadata URI
    */
    'metadataUri'?: string;
    /**
    * Metadata URI Hash
    */
    'metadataUriHash'?: string;
    /**
    * Trust Token
    */
    'trustAnchorToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "string"
        },
        {
            "name": "partNumber",
            "baseName": "part_number",
            "type": "string"
        },
        {
            "name": "serialNumber",
            "baseName": "serial_number",
            "type": "string"
        },
        {
            "name": "metadataUri",
            "baseName": "metadata_uri",
            "type": "string"
        },
        {
            "name": "metadataUriHash",
            "baseName": "metadata_uri_hash",
            "type": "string"
        },
        {
            "name": "trustAnchorToken",
            "baseName": "trust_anchor_token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GenerateObitChecksumRequest.attributeTypeMap;
    }
}

