/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Returns steps that used for DID generation
*/
export class GenerateObitDIDResponse {
    /**
    * Serial Number Hash is sha256 of the Serial Number input
    */
    'serialNumberHash'?: string;
    /**
    * Universal Serial Number
    */
    'usn'?: string;
    /**
    * DID
    */
    'did'?: string;
    /**
    * Base58
    */
    'usnBase58'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "serialNumberHash",
            "baseName": "serial_number_hash",
            "type": "string"
        },
        {
            "name": "usn",
            "baseName": "usn",
            "type": "string"
        },
        {
            "name": "did",
            "baseName": "did",
            "type": "string"
        },
        {
            "name": "usnBase58",
            "baseName": "usn_base58",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GenerateObitDIDResponse.attributeTypeMap;
    }
}

