/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* OBADA account import payload
*/
export class ImportAccountRequest {
    /**
    * OBADA account
    */
    'privateKey': string;
    /**
    * Associative account name
    */
    'accountName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "privateKey",
            "baseName": "private_key",
            "type": "string"
        },
        {
            "name": "accountName",
            "baseName": "account_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ImportAccountRequest.attributeTypeMap;
    }
}

