/**
 * OBADA Client Helper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LocalObitDocumentsInner } from './localObitDocumentsInner';
import { LocalObitMetadataInner } from './localObitMetadataInner';
import { LocalObitStructuredDataInner } from './localObitStructuredDataInner';

export class LocalObit {
    /**
    * Owner is the person/entity that owns the obit and the physical asset it represents.
    */
    'owner': string;
    /**
    * Represent available Obit statuses:   - FUNCTIONAL   - NON_FUNCTIONAL   - DISPOSED   - STOLEN   - DISABLED_BY_OWNER 
    */
    'obitStatus': LocalObit.ObitStatusEnum;
    /**
    * Waiting more specific details from Rohi
    */
    'manufacturer': string;
    /**
    * Manufacturer provided. In cases where no part number is provided for the product, use model, or the most specific ID available from the manufacturer. MWCN2LL/A (an iPhone 11 Pro, Silver, 256GB, model A2160)
    */
    'partNumber': string;
    /**
    * Serial Number
    */
    'serialNumber': string;
    /**
    * Get description from Rohi
    */
    'metadata'?: Array<LocalObitMetadataInner>;
    /**
    * To generate this link, take an SHA-256 hash of the document, and link to it as https://www.some-website.com?h1=hash-of-document. Note this does not yet adhere to the hashlink standard. 
    */
    'documents'?: Array<LocalObitDocumentsInner>;
    /**
    * Same as metadata but bigger. Key (string) => Value (string) (hash per line sha256(key + value))
    */
    'structuredData'?: Array<LocalObitStructuredDataInner>;
    'modifiedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "obitStatus",
            "baseName": "obit_status",
            "type": "LocalObit.ObitStatusEnum"
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "string"
        },
        {
            "name": "partNumber",
            "baseName": "part_number",
            "type": "string"
        },
        {
            "name": "serialNumber",
            "baseName": "serial_number",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "Array<LocalObitMetadataInner>"
        },
        {
            "name": "documents",
            "baseName": "documents",
            "type": "Array<LocalObitDocumentsInner>"
        },
        {
            "name": "structuredData",
            "baseName": "structured_data",
            "type": "Array<LocalObitStructuredDataInner>"
        },
        {
            "name": "modifiedAt",
            "baseName": "modified_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return LocalObit.attributeTypeMap;
    }
}

export namespace LocalObit {
    export enum ObitStatusEnum {
        Functional = <any> 'FUNCTIONAL',
        NonFunctional = <any> 'NON_FUNCTIONAL',
        Disposed = <any> 'DISPOSED',
        Stolen = <any> 'STOLEN',
        DisabledByOwner = <any> 'DISABLED_BY_OWNER'
    }
}
