/**
 * OBADA Client Helper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Document hashlink
*/
export class LocalObitDocumentsInner {
    /**
    * Associative name of hashlink
    */
    'name': string;
    /**
    * Hashlink
    */
    'hashlink': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "hashlink",
            "baseName": "hashlink",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LocalObitDocumentsInner.attributeTypeMap;
    }
}

