/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Mnemonic for seeding the wallet response
*/
export class MnemonicRequest {
    /**
    * Mnemonic for seeding
    */
    'mnemonic': string;
    /**
    * Flag that specify if exisiting wallet should be replaced, if false is send then error will be send back
    */
    'force'?: boolean = false;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mnemonic",
            "baseName": "mnemonic",
            "type": "string"
        },
        {
            "name": "force",
            "baseName": "force",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return MnemonicRequest.attributeTypeMap;
    }
}

