/**
 * OBADA Client Helper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ObitDefinition {
    'serialHash'?: string;
    'usn'?: string;
    'obitDid'?: string;
    'usnBase58'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "serialHash",
            "baseName": "serial_hash",
            "type": "string"
        },
        {
            "name": "usn",
            "baseName": "usn",
            "type": "string"
        },
        {
            "name": "obitDid",
            "baseName": "obit_did",
            "type": "string"
        },
        {
            "name": "usnBase58",
            "baseName": "usn_base58",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ObitDefinition.attributeTypeMap;
    }
}

