/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Obit } from './obit';
import { ObitsMeta } from './obitsMeta';

/**
* Obits search response
*/
export class Obits {
    'data'?: Array<Obit>;
    'meta'?: ObitsMeta;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<Obit>"
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "ObitsMeta"
        }    ];

    static getAttributeTypeMap() {
        return Obits.attributeTypeMap;
    }
}

