/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* New Obit request payload.
*/
export class ObitHistory {
    /**
    * OBADA decentralized identifier (max length Rohi?)
    */
    'obitDid'?: string;
    /**
    * History event
    */
    'event'?: string;
    'oldValues'?: object;
    'newValues'?: object;
    'createdAt'?: Date;
    'updatedAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "obitDid",
            "baseName": "obit_did",
            "type": "string"
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "string"
        },
        {
            "name": "oldValues",
            "baseName": "old_values",
            "type": "object"
        },
        {
            "name": "newValues",
            "baseName": "new_values",
            "type": "object"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return ObitHistory.attributeTypeMap;
    }
}

