/**
 * OBADA Client Helper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ObitDid {
    /**
    * OBADA decentralized identifier (max length Rohi?)
    */
    'obitDid': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "obitDid",
            "baseName": "obit_did",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ObitDid.attributeTypeMap;
    }
}

