/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Document } from './document';

/**
* OBADA record.
*/
export class Obit {
    /**
    * OBADA decentralized identifier
    */
    'did'?: string;
    /**
    * Test An 8-12 character “URL Shortened” obit. Create the USN by Base(58) encoding the OBIT ID. Take the first 8 characters. Check for duplicates. With 16 million OBITs there is a 40% chance of collision. If so, add 4 characters. Repeat as necessary until a unique USN is generated. 
    */
    'usn'?: string;
    /**
    * Owner is the person/entity that owns the obit and the physical asset it represents. Format is a DID like did:obada:owner:1234. However in the current version only test numbers will be used.
    */
    'owner'?: string;
    /**
    * Waiting more specific details from Rohi
    */
    'manufacturer': string;
    /**
    * Manufacturer provided. In cases where no part number is provided for the product, use model, or the most specific ID available from the manufacturer. MWCN2LL/A (an iPhone 11 Pro, Silver, 256GB, model A2160)
    */
    'partNumber': string;
    /**
    * Serial number hashed with sha256 hash function
    */
    'serialNumberHash'?: string;
    /**
    * JWT token from the trust anchor
    */
    'trustAnchorToken'?: string;
    /**
    * Documents that are attached to Obit
    */
    'documents'?: Array<Document>;
    /**
    * Hash calculated by SHA256 (previous Obit checksum + Obit data). 
    */
    'checksum'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "did",
            "baseName": "did",
            "type": "string"
        },
        {
            "name": "usn",
            "baseName": "usn",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "string"
        },
        {
            "name": "partNumber",
            "baseName": "part_number",
            "type": "string"
        },
        {
            "name": "serialNumberHash",
            "baseName": "serial_number_hash",
            "type": "string"
        },
        {
            "name": "trustAnchorToken",
            "baseName": "trust_anchor_token",
            "type": "string"
        },
        {
            "name": "documents",
            "baseName": "documents",
            "type": "Array<Document>"
        },
        {
            "name": "checksum",
            "baseName": "checksum",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Obit.attributeTypeMap;
    }
}

