/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Sending tokens payload
*/
export class SendCoinsRequest {
    'recepientAddress': string;
    'amount': string;
    'denom': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recepientAddress",
            "baseName": "recepient_address",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "denom",
            "baseName": "denom",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SendCoinsRequest.attributeTypeMap;
    }
}

