/**
 * OBADA API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UnprocessableEntityFieldsInner } from './unprocessableEntityFieldsInner';

/**
* A typical 422 error.
*/
export class UnprocessableEntity {
    'error'?: string = 'data validation error';
    'fields'?: Array<UnprocessableEntityFieldsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<UnprocessableEntityFieldsInner>"
        }    ];

    static getAttributeTypeMap() {
        return UnprocessableEntity.attributeTypeMap;
    }
}

